In [40]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [41]:
sql = '''
SELECT "OFFENSE_DESCRIPTION",
       "OCCURRED_ON_DATE"
FROM "b973d8cb-eeb2-4e7e-99da-c92938efc9c0"
LIMIT 10000
'''

In [42]:
bpd_logs = "https://data.boston.gov/api/3/action/datastore_search_sql"

In [43]:
import urllib, requests

In [44]:
bpd_logs = "https://data.boston.gov/api/3/action/datastore_search_sql"
url = bpd_logs + "?sql=" + urllib.parse.quote(sql)

rows = requests.get(url).json()
records = rows['result']['records']

In [45]:
records

[{'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-27 22:44:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-01-17 20:21:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-24 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'OCCURRED_ON_DATE': '2023-03-31 17:14:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-01-26 09:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-29 14:55:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-02-07 11:05:00+00'},
 {'OFFENSE_DESCRIPTION': 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
  'OCCURRED_ON_DATE': '2023-02-09 12:02:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-09 12:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-02-15 18:59:00+00'},
 {'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'OCCURRED_ON_DATE': '2023-02-18 21:43:00+00'},
 {'OFFENSE_DESCRIPTION': 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
  'OCCURRED_ON_DATE': '2023-02-22 18:11:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-04-14 01:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-03-05 20:55:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-03-07 18:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-07-02 14:27:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-02 12:57:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-02-04 17:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-02-06 15:43:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-03-16 17:47:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-16 17:24:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-14 09:54:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-03-11 10:02:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-12 18:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-02-19 06:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'OCCURRED_ON_DATE': '2023-02-19 08:28:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-02-19 10:22:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-19 12:01:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-02-19 12:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-02-19 14:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-19 17:33:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-02-19 18:07:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-19 19:02:00+00'},
 {'OFFENSE_DESCRIPTION': 'SICK ASSIST',
  'OCCURRED_ON_DATE': '2023-02-19 20:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-19 21:24:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-02-19 23:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-02-19 23:59:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'OCCURRED_ON_DATE': '2024-08-11 16:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-03-05 06:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'OPERATING UNDER THE INFLUENCE (OUI) ALCOHOL',
  'OCCURRED_ON_DATE': '2023-04-25 22:05:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-02-23 14:44:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-30 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'OPERATING UNDER THE INFLUENCE (OUI) ALCOHOL',
  'OCCURRED_ON_DATE': '2023-01-11 02:31:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-22 10:53:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-18 22:22:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-03-13 09:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-05-24 16:03:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY THEFT FROM BUILDING',
  'OCCURRED_ON_DATE': '2023-03-18 09:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-06 01:16:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-01 18:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-09 13:46:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-03-30 21:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'VANDALISM',
  'OCCURRED_ON_DATE': '2023-04-02 20:06:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-12 03:44:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-20 10:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-04-07 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-04-08 22:35:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-13 13:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-30 12:57:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-01 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'TRESPASSING',
  'OCCURRED_ON_DATE': '2023-08-04 13:51:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY SHOPLIFTING',
  'OCCURRED_ON_DATE': '2025-11-22 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-27 21:13:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-08-06 19:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-16 17:57:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-09 14:10:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-07 09:02:00+00'},
 {'OFFENSE_DESCRIPTION': 'INTIMIDATING WITNESS',
  'OCCURRED_ON_DATE': '2023-11-10 16:15:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-08-16 18:31:00+00'},
 {'OFFENSE_DESCRIPTION': 'DRUGS - POSSESSION/ SALE/ MANUFACTURING/ USE',
  'OCCURRED_ON_DATE': '2023-08-21 17:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-01-30 18:24:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-11-25 07:27:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-08-28 11:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-11-17 15:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ROBBERY',
  'OCCURRED_ON_DATE': '2023-12-01 11:25:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-05-18 22:04:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-04-12 07:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-04-10 16:41:00+00'},
 {'OFFENSE_DESCRIPTION': 'ROBBERY',
  'OCCURRED_ON_DATE': '2023-05-23 23:29:00+00'},
 {'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'OCCURRED_ON_DATE': '2023-05-24 18:49:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-26 03:47:00+00'},
 {'OFFENSE_DESCRIPTION': 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
  'OCCURRED_ON_DATE': '2024-01-25 17:53:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-29 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-05-28 16:56:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-03 09:48:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY SHOPLIFTING',
  'OCCURRED_ON_DATE': '2023-10-21 13:40:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2024-02-02 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-03-03 20:45:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-10-27 12:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-04-05 12:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-02-03 15:26:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-05-10 13:56:00+00'},
 {'OFFENSE_DESCRIPTION': 'BURGLARY - COMMERICAL',
  'OCCURRED_ON_DATE': '2023-06-06 22:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-31 11:59:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-29 14:05:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-14 06:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'OCCURRED_ON_DATE': '2023-06-01 09:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-01-07 02:51:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-13 08:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-11 16:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-26 19:58:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-06-11 02:40:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-05-27 13:48:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-15 21:29:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-06-20 20:43:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-06-24 17:12:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-07-09 17:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-18 09:45:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-06-30 14:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-06-10 15:13:00+00'},
 {'OFFENSE_DESCRIPTION': 'AUTO THEFT',
  'OCCURRED_ON_DATE': '2023-01-22 00:36:00+00'},
 {'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'OCCURRED_ON_DATE': '2023-04-02 10:52:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-07-06 21:55:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-01-07 19:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-01-07 19:31:00+00'},
 {'OFFENSE_DESCRIPTION': 'WARRANT ARREST - OUTSIDE OF BOSTON WARRANT',
  'OCCURRED_ON_DATE': '2023-07-19 19:57:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-07-30 09:23:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-30 12:37:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-15 21:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-26 08:49:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-08-06 16:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-06-18 16:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-27 16:40:00+00'},
 {'OFFENSE_DESCRIPTION': 'ROBBERY',
  'OCCURRED_ON_DATE': '2023-07-25 12:45:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-08-18 10:04:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-07-01 11:29:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-05-19 11:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-08-30 08:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-16 18:32:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-17 09:46:00+00'},
 {'OFFENSE_DESCRIPTION': 'FRAUD - IMPERSONATION',
  'OCCURRED_ON_DATE': '2023-07-14 13:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-08-12 21:39:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-05-24 14:52:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-08-13 16:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'OCCURRED_ON_DATE': '2023-06-05 21:14:00+00'},
 {'OFFENSE_DESCRIPTION': 'SICK ASSIST',
  'OCCURRED_ON_DATE': '2023-09-13 10:48:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY THEFT FROM BUILDING',
  'OCCURRED_ON_DATE': '2023-08-02 18:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-08-23 22:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-21 16:22:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-04-10 20:37:00+00'},
 {'OFFENSE_DESCRIPTION': 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
  'OCCURRED_ON_DATE': '2023-09-22 11:57:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-09-27 07:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-07-21 19:33:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY ALL OTHERS',
  'OCCURRED_ON_DATE': '2024-01-01 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-25 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-26 12:18:00+00'},
 {'OFFENSE_DESCRIPTION': 'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
  'OCCURRED_ON_DATE': '2023-10-20 18:25:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-10-22 01:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'BURGLARY - RESIDENTIAL',
  'OCCURRED_ON_DATE': '2023-11-05 01:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'EXTORTION OR BLACKMAIL',
  'OCCURRED_ON_DATE': '2023-11-07 17:19:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-29 18:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-08-04 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-11-13 06:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'WARRANT ARREST - OUTSIDE OF BOSTON WARRANT',
  'OCCURRED_ON_DATE': '2023-09-20 10:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2024-09-26 13:27:00+00'},
 {'OFFENSE_DESCRIPTION': 'SICK/INJURED/MEDICAL - PERSON',
  'OCCURRED_ON_DATE': '2023-11-06 06:20:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-20 02:40:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-09-26 18:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'MISSING PERSON',
  'OCCURRED_ON_DATE': '2023-10-01 23:04:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY THEFT FROM BUILDING',
  'OCCURRED_ON_DATE': '2023-10-04 13:54:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-10-06 17:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-22 00:18:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-17 12:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'OPERATING UNDER THE INFLUENCE (OUI) ALCOHOL',
  'OCCURRED_ON_DATE': '2023-11-29 01:33:00+00'},
 {'OFFENSE_DESCRIPTION': 'BREAKING AND ENTERING (B&E) MOTOR VEHICLE',
  'OCCURRED_ON_DATE': '2023-10-12 02:03:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-01-29 03:43:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-09-26 10:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-30 20:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-03 13:16:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-10-01 20:55:00+00'},
 {'OFFENSE_DESCRIPTION': 'SICK ASSIST',
  'OCCURRED_ON_DATE': '2023-03-12 16:28:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-11-09 01:36:00+00'},
 {'OFFENSE_DESCRIPTION': 'LARCENY THEFT FROM BUILDING',
  'OCCURRED_ON_DATE': '2023-11-09 12:05:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-10-26 11:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-12-10 11:33:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-12-15 09:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-12-16 11:44:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-11-06 01:17:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-11-06 01:55:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-11-06 02:13:00+00'},
 {'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'OCCURRED_ON_DATE': '2023-12-16 07:50:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-12-30 11:54:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-02-27 00:00:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2023-11-18 15:34:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'OCCURRED_ON_DATE': '2023-09-26 20:35:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-03-09 02:05:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2023-12-02 06:30:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-12-06 23:33:00+00'},
 {'OFFENSE_DESCRIPTION': 'HARASSMENT/ CRIMINAL HARASSMENT',
  'OCCURRED_ON_DATE': '2023-12-07 21:24:00+00'},
 {'OFFENSE_DESCRIPTION': 'ROBBERY',
  'OCCURRED_ON_DATE': '2024-01-05 14:40:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2023-03-31 08:02:00+00'},
 {'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'OCCURRED_ON_DATE': '2024-01-08 16:36:00+00'},
 {'OFFENSE_DESCRIPTION': 'AUTO THEFT',
  'OCCURRED_ON_DATE': '2023-12-19 21:39:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2024-01-15 12:38:00+00'},
 {'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'OCCURRED_ON_DATE': '2024-01-03 15:12:00+00'},
 {'OFFENSE_DESCRIPTION': 'ROBBERY',
  'OCCURRED_ON_DATE': '2024-01-03 16:08:00+00'},
 {'OFFENSE_DESCRIPTION': 'VERBAL DISPUTE',
  'OCCURRED_ON_DATE': '2024-01-08 04:35:00+00'},
 {'OFFENSE_DESCRIPTION': 'THREATS TO DO BODILY HARM',
  'OCCURRED_ON_DATE': '2023-12-28 22:26:00+00'},
 {'OFFENSE_DESCRIPTION': 'BURGLARY - COMMERICAL',
  'OCCURRED_ON_DATE': '2024-01-11 10:00:00+00'},

In [46]:
import pandas as pd

df = pd.DataFrame(records)
df.head()

    OFFENSE_DESCRIPTION        OCCURRED_ON_DATE
0    INVESTIGATE PERSON  2023-01-27 22:44:00+00
1        VERBAL DISPUTE  2023-01-17 20:21:00+00
2    INVESTIGATE PERSON  2023-01-24 00:00:00+00
3  INVESTIGATE PROPERTY  2023-03-31 17:14:00+00
4  ASSAULT - AGGRAVATED  2023-01-26 09:00:00+00

In [47]:
top_crimes = (
    df['OFFENSE_DESCRIPTION']
    .value_counts()
    .head(5)
    .reset_index()
)

top_crimes.columns = ['OFFENSE_DESCRIPTION', 'COUNT']
top_crimes

                     OFFENSE_DESCRIPTION  COUNT
0                     INVESTIGATE PERSON   1158
1                            SICK ASSIST   1019
2  M/V - LEAVING SCENE - PROPERTY DAMAGE    510
3                    LARCENY SHOPLIFTING    443
4                       ASSAULT - SIMPLE    426

In [48]:
import plotly.express as px

fig1 = px.bar(
    top_crimes,
    x='OFFENSE_DESCRIPTION',
    y='COUNT',
    title='Top 5 Crime Types in Boston',
)

fig1.show()

In [54]:
df['OCCURRED_ON_DATE'] = pd.to_datetime(df['OCCURRED_ON_DATE'], errors='coerce')
df = df.dropna(subset=['OCCURRED_ON_DATE', 'OFFENSE_DESCRIPTION'])
df['HOUR'] = df['OCCURRED_ON_DATE'].dt.hour

In [57]:
top3 = top_crimes['OFFENSE_DESCRIPTION'].head(3).tolist()

df_top3 = df[df['OFFENSE_DESCRIPTION'].isin(top3)]

hourly_patterns = (
    df_top3.groupby(['HOUR', 'OFFENSE_DESCRIPTION'])
    .size()
    .reset_index(name='COUNT')
)

hourly_patterns.head()

   HOUR                    OFFENSE_DESCRIPTION  COUNT
0     0                     INVESTIGATE PERSON    102
1     0  M/V - LEAVING SCENE - PROPERTY DAMAGE     35
2     0                            SICK ASSIST     70
3     1                     INVESTIGATE PERSON     22
4     1  M/V - LEAVING SCENE - PROPERTY DAMAGE     11

In [58]:
fig2 = px.line(
    hourly_patterns,
    x='HOUR',
    y='COUNT',
    color='OFFENSE_DESCRIPTION',
    markers=True,
    title='Hourly Crime Patterns for Top 3 Crimes'
)

fig2.show()